language: go
go:
- 1.x

services:
- docker

script:
- go test -v ./...
- docker build -t orgplace/trafficquota .

deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push orgplace/trafficquota
