language: go
go:
- "1.11.x"

services:
- docker

script:
- go test -v ./...
- docker build -t orgplace/trafficquota .

deploy:
  skip_cleanup: true
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push orgplace/trafficquota
