language: go
go:
- "1.11.x"

services:
- docker

script:
- go test -race -coverprofile=profile.out -covermode=atomic -parallel 2 ./...
- docker build -t orgplace/trafficquota .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push orgplace/trafficquota

after_success:
- bash <(curl -s https://codecov.io/bash)
